openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
#   /log/:
#     get:
#       description: get all logs
#       responses: 
#         200:
#           description: Ok.
#           content:
#             application/json: 
#               schema:
#                 type: array
#                 items:
#                   $ref: '../schema/log.yaml#/components/schemas/log'
#         201:
#           $ref: "#/components/responses/hi"

# components: 
#   responses:
#     hi:
#       description: Ok.
#       content:
#         application/json: 
#           schema:
#             type: array
#             items:
#               $ref: '../schema/log.yaml#/components/schemas/log'