openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: 
  /log/: 
    get:
      security:
        - BearerToken: []
      parameters:
        - $ref: '#/components/parameters/bearer'
      tags:
        - "log"
      summary: list all logs
      description: list all logs for the current user
      responses:
        200:
          $ref: '#/components/responses/logs'
        401:
          $ref: '#/components/responses/TokenFailed'
    post:
      security:
        - BearerToken: []
      parameters:
        - $ref: '#/components/parameters/bearer'
      tags:
        - "log"
      summary: create new log
      description: create new log for the current user
      requestBody:
        required: true
        description: properties like title, amount, category and note
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - amount
              properties:
                title:
                  type: string
                  example: buy new TV
                amount:
                  type: string
                  example: \#000000
                notes:
                  type: string
                  example: New_Icon              
                category:
                  type: string
                  example: 63da2a0a643dd3aa49f5c6b1
      responses:
        200:
          $ref: '#/components/responses/log'
        400:
          $ref: '#/components/responses/SomeFieldsRequired'
        401:
          $ref: '#/components/responses/TokenFailed'
  /log/{id}:
    parameters:
      - $ref: '#/components/parameters/byId'
    get:
      security:
        - BearerToken: []
      parameters:
        - $ref: '#/components/parameters/bearer'
      tags:
        - "log"
      summary: get log
      description: create new log for the current user
      responses:
        200:
          $ref: '#/components/responses/log'
        400:
          $ref: '#/components/responses/SomeFieldsRequired'
        401:
          $ref: '#/components/responses/TokenFailed'
        404:
          $ref: '#/components/responses/ResourceWasNotFound'
    put:
      security:
        - BearerToken: []
      parameters:
        - $ref: '#/components/parameters/bearer'
      requestBody:
        required: true
        description: properties like title, amount, category and note
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: buy new TV
                amount:
                  type: string
                  example: \#000000
                notes:
                  type: string
                  example: New_Icon              
                category:
                  type: string
                  example: 63da2a0a643dd3aa49f5c6b1
      tags:
        - "log"
      summary: update log
      description: update log by id
      responses:
        200:
          $ref: '#/components/responses/log'
        401:
          $ref: '#/components/responses/TokenFailed'
        404:
          $ref: '#/components/responses/ResourceWasNotFound'
    delete:
      security:
        - BearerToken: []
      parameters:
        - $ref: '#/components/parameters/bearer'
      tags:
        - "log"
      summary: delete log
      description: delete log by id
      responses:
        200:
          description: Ok
          content:
            application/json: 
              x-success: true
              schema: {}
        401:
          $ref: '#/components/responses/TokenFailed'
        404:
          $ref: '#/components/responses/ResourceWasNotFound'


components:
  parameters:
    byId:
      $ref: "../paths/__parameters.yaml#/components/parameters/byId"
    bearer:
      $ref: "../security/http.yaml#/components/parameters/bearer"

  responses:
    log:
      $ref: "../schema/log.yaml#/components/responses/log"
    logs:
      $ref: "../schema/log.yaml#/components/responses/logs"
    SessionEnded:
      $ref: "../errors/SessionEnded.yaml#/components/responses/SessionEnded"
    MalformedToken:
      $ref: "../errors/MalformedToken.yaml#/components/responses/MalformedToken"
    TokenFailed:
      $ref: "../errors/TokenFailed.yaml#/components/responses/TokenFailed"
    SomeFieldsRequired:
      $ref: "../errors/SomeFieldsRequired.yaml#/components/responses/SomeFieldsRequired"
    ResourceWasNotFound:
      $ref: "../errors/ResourceWasNotFound.yaml#/components/responses/ResourceWasNotFound"
servers:
  - url: https://localhost:{port}/api/{version}
    description: development localhost servers
    variables:
      version:
        default: v1
      port:
        default: '8811'
