openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: 
  /profile/status/: 
    get:
      tags:
        - "profile"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: 'joeDue@gmail.com'
      summary: authentication status
      description: |
        when provided with email, this will resolve to
        all available authentication methods for given email
      responses:
        400:
          $ref: '#/components/responses/SomeFieldsRequired'
        200:
          description: Ok
          content:
            application/json: 
              x-success: true
              examples:
                singed up:
                  description: singed up with multiple authentication methods
                  value: ['local', 'google']
                not signed up:
                  description: email is not signed up
                  value: []
              schema:
                $ref: "../schema/profile.yaml#/components/schemas/providers"
  /profile/:
    get:
      security:
        - BearerToken: []
      parameters:
        - $ref: '#/components/parameters/bearer'
      tags:
        - "profile"
      summary: get profile
      description: retrieve profile info
      responses:
        200:
          $ref: '#/components/responses/profile'
        401:
          $ref: '#/components/responses/TokenFailed'
    put:
      security:
        - BearerToken: []
      parameters:
        - $ref: '#/components/parameters/bearer'
      requestBody:
        description: fields to update
        content:
          application/json:
            schema:
              type: object
              properties:
                displayName:
                  type: string
                  example: Joe Doe
                picture:
                  type: string
                  example: https ://example.com/path/to/img"
      tags:
        - "profile"
      summary: update profile 
      description: update profile information
      responses:
        200:
          $ref: '#/components/responses/profile'
        401:
          $ref: '#/components/responses/TokenFailed'

  /profile/password/:
    put: 
      security:
        - BearerToken: []
      parameters:
        - $ref: '#/components/parameters/bearer'
      requestBody:
        description: update the password
        content:
          application/json:
            schema:
              type: object
              required:
                - newPassword
              properties:
                oldPassword:
                  description: may be required if `local` authenticate is provided
                  type: string
                  example: 12345567
                newPassword:
                  type: string
                  example: 12345567differentPassword
      tags:
        - "profile"
      summary: (re)set password 
      description: update users password
      responses:
        200:
          $ref: '#/components/responses/profile'
        400:
          $ref: '#/components/responses/SomeFieldsRequired'
        401:
          $ref: '#/components/responses/TokenFailed'

components:
  parameters:
    bearer:
      $ref: "../security/http.yaml#/components/parameters/bearer"

  responses:
    profile:
      $ref: "../schema/profile.yaml#/components/responses/profile"
    SessionEnded:
      $ref: "../errors/SessionEnded.yaml#/components/responses/SessionEnded"
    MalformedToken:
      $ref: "../errors/MalformedToken.yaml#/components/responses/MalformedToken"
    TokenFailed:
      $ref: "../errors/TokenFailed.yaml#/components/responses/TokenFailed"
    SomeFieldsRequired:
      $ref: "../errors/SomeFieldsRequired.yaml#/components/responses/SomeFieldsRequired"
servers:
  - url: https://localhost:{port}/api/{version}
    description: development localhost servers
    variables:
      version:
        default: v1
      port:
        default: '8811'
