# meant to run only an ephemeral database
version: '3'
services:
  mongo:
    image: mongo:3.6-xenial
    hostname: mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=e2eroot
      - MONGO_INITDB_ROOT_PASSWORD=e2epass
