openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:

  schemas: 
    log:
      allOf:
        - $ref: '../schema/database.yaml#/components/schemas/mongoDoc'
        - $ref: '../schema/database.yaml#/components/schemas/mongoTime'
        - type: object
          required:
            - title
            - amount
            - createdBy
          properties:
            title: 
              type: string
              example: buy new TV
            amount:
              type: number
              example: 400
            createdBy:
              type: string
              example: 63da2a0a643dd3aa49f5c6b1
            note:
              type: string
              example: new 40" plasma tv from flea market
            category:
              $ref: './category.yaml#/components/schemas/categoryPopulated'
    
