openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  responses:
    categories:
      description: Ok
      content:
        application/json: 
          x-success: true
          x-paged: true
          examples:
            basic:
              description: basic example
              value:
                [{"_id": "626819066b8ac48b612dda69",
                __v: 0,
                title: "Entertainment",
                color: "#333",
                icon: "Fun_Face_Icon",
                createdBy: "63da2a0a643dd3aa49f5c6b1"}]
            no data:
              description: empty data
              value: []
          schema:
            type: array
            items:
              $ref: "#/components/schemas/category"
  schemas:
    category:
      $ref: "../schema/category.yaml#/components/schemas/category"
 