openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  responses:
    UnAuthorized:
      description: authentication failed, Authorization is required
      content:
        application/json:
          x-failed: true
          schema:
            type: object
            properties:
              status:
                type: number
                default: 442
                enum:
                  - 401
                  - 442
              message:
                description: more details
                example: authentication failed
                type: string
              name:
                type: string
                default: UnAuthorized
              details:
                type: object
