[package]
default-run="pani-puri"
name = "pani-puri"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
async-graphql = "5.0.10"
async-graphql-actix-web = "5.0.10"
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
