# docker compose to run postgresql server
# docker-compose -f postgress.compose.yaml up -d
# docker-compose -f postgress.compose.yaml down
name: postgresql
version: '3.7'
services:
  postgresql:
    image: postgres:12.1-alpine
    container_name: postgresql
    restart: always
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
