version: '2'

services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - back
  backend:
    build: ./backend
    networks:
      - back
      - front
    ports:
      - "443:443"
  front:
    image: 'node:alpine'
    networks:
      - front
    
    ports:
      - "80:80"

networks:
  front: {}
  back: {}
