version: "3.9"
services:
  dev-api:
    build: .
    environment:
      - MONGO_STRING=mongodb://mongo:27017/money-tracker
    ports:
      - "8811:8811"
    volumes:
      - './:/usr/src/app'
    entrypoint: [ "npm", "run", "dev"]
    depends_on:
      - dev-mongo

  dev-mongo:
    image: "mongo:3.6-xenial"
    ports:
      - '27017:27017'


networks:
  default: