openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
components:
  securitySchemes:
    emailAuth:
      type: http
      scheme: basic
      description: |
        use email and password to gain
        user's profile along with the
        token.
    token:
      type: http
      scheme: bearer
      description: |
        this is the standard way to authenticate
        requests, such a token can be obtained via
        emailAuth or googleAuth
  schemas:
    mongoDoc:
      description: |
        this type is used as composition with other
        type @example:
        ```
        allOf:
        - $ref: '#/components/schemas/mongoDoc'
        - $ref: '#/components/schemas/log'
        ```
      type: object
      required:
        - _id
        - __v
      properties:
        _id:
          type: string
        __v:
          type: string
          enum:
            - 0
    mongoTime:
      description: |
        this type is used as composition with other
        type @example:
        ```
        allOf:
        - $ref: '#/components/schemas/mongoTime'
        - $ref: '#/components/schemas/log'
        ```
      type: object
      required:
        - createdAt
        - updatedAt
      properties:
        createdAt:
          type: string
        updatedAt:
          type: string
    profile:
      allOf:
        - $ref: "#/components/schemas/mongoDoc"
        - type: object
          required:
            - userName
            - email
            - providers
          properties:
            userName:
              type: string
            email:
              type: string
            providers:
              type: array
              items:
                type: string
                enum:
                  - local
                  - google
            picture:
              type: string
paths:
  /api/v1/auth/local/login:
    get:
      security:
        - emailAuth: []
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/profile"
  /api/v1/log/:
    get:
      description: get all logs
      responses:
        "200":
          description: Everything went fine.
    post:
      description: add one log
      responses:
        "200":
          description: get all logs.
tags: []
