openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  responses:
    MalformedToken:
      description: token is corrupt 
      content:
        application/json:
          x-failed: true
          schema:
            type: object
            properties:
              status:
                type: number
                default: 442
                enum:
                  - 401
                  - 442
              message:
                description: more details
                example: the token is either corrupted or invalid
                type: string
              name:
                type: string
                default: MalformedToken
              details:
                type: object
                properties:
                  name:
                    type: string
                    default: JsonWebTokenError
                  message:
                    type: string
                    default: invalid signature


    
