openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  responses:
    ResourceWasNotFound:
      description: current resource doesn't exist
      content:
        application/json:
          x-failed: true
          schema:
            type: object
            properties:
              status:
                type: number
                default: 404
              message:
                type: string
                default: couldn't find the target
              name:
                type: string
                default: ResourceWasNotFound
              details:
                type: object

    
