openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  responses:
    SessionEnded:
      description: the token/session has expired, login again 
      content:
        application/json:
          x-failed: true
          schema:
            type: object
            properties:
              status:
                type: number
                enum: [401, 441]
                default: 441
              message:
                description: session has ended
                example: session has ended
                type: string
              name:
                type: string
                default: SessionEnded
              details:
                type: object
                properties:
                  expiredAt:
                    type: string
                    example: 2023-02-03T09:06:50.000Z


    
