openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  responses:
    TokenFailed:
      description: authentication via bearer token has failed 
      content:
        application/json:
          x-failed: true
          schema:
            type: object
            properties:
              status:
                type: number
                default: 401
              message:
                description: more details
                example: authentication failed
                type: string
              name:
                type: string
                default: TokenFailed
              details:
                type: object
                required:
                  - 'type'
                properties:
                  type:
                    type: string
                    enum:
                      - 'JsonWebTokenError'
                      - 'TokenExpiredError'
                      - 'NoTokenWasProvided'
                      - 'UnspecifiedError'
                    example : TokenExpiredError

                  date:
                    type: string
                    example: '2022-04-26T16:08:38.276Z'

    
