openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  responses:
    UserAlreadyExist:
      description: User already exist
      content:
        application/json:
          x-failed: true
          schema:
            type: object
            properties:
              status:
                type: number
                default: 409
              message:
                example: User already exist
                type: string
              name:
                type: string
                default: UserAlreadyExist
              details:
                type: object


    
