version: '3'
services:
  main-service:
    build:
      dockerfile: Dockerfile
      context: ../../
      args:
        Package_name: backend
    command: [ "npm", "run", "dev", "-w", "backend" ]
    env_file:
      - ./.env
    environment:
      - MONGO_STRING=mongodb://mongo:27017/testing
    ports:
      - "8080:8081"
    networks:
      - default
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6-xenial
    networks:
      - default

networks:
  default:
    driver: bridge