openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  examples:
    category:
      summary: example when requesting category
      value:
        _id: 63da2a0a643dd3aa49f5c6b1
        __v: 0
        title: Entertainment
        color: Blue
        icon: Fun_Icon
        createdBy: 63da2a0a643dd3aa49f5c6b1 
    category_populated:
      summary: when populating category properties like createdBy, __v will be deleted
      value:
        _id: 123xxxxxxxxxxxx
        title: Gas
        color: Green
        icon: GAS_ICON

  schemas:
    category:
      allOf:
        - $ref: '#/components/schemas/mongoDoc'
        - type: object
          required:
            - title
            - createdBy
          properties:
            _id:
              type: string
              example: 63da2a0a643dd3aa49f5c6b1
            __v:
              type: string
              example: 0
              default: 0

            title: 
              type: string
              example: Entertainment
            color:
              type: string
              example: "#333"
            icon:
              type: string
              example: Fun_Face_Icon
            createdBy:
              type: string
              example: 63da2a0a643dd3aa49f5c6b1
    categoryPopulated:
        type: object
        properties:
          _id: 
            type: string
            example: 63da2a0a643dd3aa49f5c6b1
          title: 
            type: string
            example: Entertainment
          color:
            type: string
            example: "#333"
          icon:
            type: string
            example: Fun_Face_Icon

    mongoDoc: 
      $ref: "./database.yaml#/components/schemas/mongoDoc"
    profile: 
      $ref: "./profile.yaml#/components/schemas/profile"
    mongoTime: 
      $ref: "./database.yaml#/components/schemas/mongoTime"
