openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  responses:
    category:
      description: Ok
      content:
        application/json: 
          x-success: true
          schema:
            $ref: "#/components/schemas/category"
    categories:
      description: Ok
      content:
        application/json: 
          x-success: true
          x-paged: true
          examples:
            basic:
              description: basic example
              value:
                [{"_id": "626819066b8ac48b612dda69",
                __v: 0,
                title: "Entertainment",
                color: "#333",
                icon: "Fun_Face_Icon",
                createdBy: "63da2a0a643dd3aa49f5c6b1"}]
            no data:
              description: empty data
              value: []
          schema:
            type: array
            items:
              $ref: "#/components/schemas/category"
  schemas:
    category:
      allOf:
        - $ref: '#/components/schemas/mongoDoc'
        - type: object
          required:
            - title
            - createdBy
          properties:
            # _id:
            #   type: string
            #   example: 63da2a0a643dd3aa49f5c6b1
            # __v:
            #   type: string
            #   example: 0
            #   default: 0
            title: 
              type: string
              example: Entertainment
            color:
              type: string
              example: "#333"
            icon:
              type: string
              example: Fun_Face_Icon
            createdBy:
              type: string
              example: 63da2a0a643dd3aa49f5c6b1
    categoryPopulated:
      type: object
      properties:
        _id: 
          type: string
          example: 63da2a0a643dd3aa49f5c6b1
        title: 
          type: string
          example: Entertainment
        color:
          type: string
          example: "#333"
        icon:
          type: string
          example: Fun_Face_Icon

    mongoDoc: 
      $ref: "./database.yaml#/components/schemas/mongoDoc"
    # profile: 
    #   $ref: "./profile.yaml#/components/schemas/profile"
    # mongoTime: 
    #   $ref: "./database.yaml#/components/schemas/mongoTime"
