openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  responses:
    log:
      description: Ok
      content:
        application/json: 
          x-success: true
          schema:
            $ref: "#/components/schemas/log"
    logs:
      description: Ok
      content:
        application/json: 
          x-success: true
          x-paged: true
          examples:
            basic:
              description: basic example
              value: [{
                "_id": "626819066b8ac48b612dda69",
                "__v": 0,
                "createdAt": "2022-04-26T16:08:38.276Z",
                "updatedAt": "2022-04-26T16:08:38.276Z",
                "title": "buy new TV",
                "amount": 400,
                "createdBy": "63da2a0a643dd3aa49f5c6b1",
                "note": "new 40\" plasma tv from flea market",
                "category": {
                  "_id": "63da2a0a643dd3aa49f5c6b1",
                  "title": "Entertainment",
                  "color": "#333",
                  "icon": "Fun_Face_Icon"}}]
            no data:
              description: empty data
              value: []
          schema:
            type: array
            items:
              $ref: "#/components/schemas/log"

  schemas: 
    log:
      allOf:
        - $ref: '#/components/schemas/mongoDoc'
        - $ref: '#/components/schemas/mongoTime'
        - type: object
          required:
            - title
            - amount
            - createdBy
          properties:
            title: 
              type: string
              example: buy new TV
            amount:
              type: number
              example: 400
            createdBy:
              type: string
              example: 63da2a0a643dd3aa49f5c6b1
            note:
              type: string
              example: new 40" plasma tv from flea market
            category:
              $ref: '#/components/schemas/categoryPopulated'
    mongoDoc:
      $ref: "./database.yaml#/components/schemas/mongoDoc"
    mongoTime:
      $ref: "./database.yaml#/components/schemas/mongoTime"
    profile:
      $ref: "./profile.yaml#/components/schemas/profile"
    categoryPopulated:
      $ref: "./category.yaml#/components/schemas/categoryPopulated"

    
