openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  examples:
    log:
      summary: log example
      value:
        title: buy new TV
        amount: 500
        note: new 40" plasma tv from flea market
        createdBy: 
          $ref: './profile.yaml#/components/examples/profile/value'
        category: 
          $ref: './category.yaml#/components/examples/category_populated/value'

  schemas: 
    log:
      allOf:
        - $ref: '#/components/schemas/mongoDoc'
        - $ref: '#/components/schemas/mongoTime'
        - type: object
          required:
            - title
            - amount
            - createdBy
          properties:
            title: 
              type: string
            amount:
              type: number
            createdBy:
              $ref: '#/components/schemas/profile'
            note:
              type: string
            category:
              $ref: '#/components/schemas/categoryPopulated'
    mongoDoc:
      $ref: "./database.yaml#/components/schemas/mongoDoc"
    mongoTime:
      $ref: "./database.yaml#/components/schemas/mongoTime"
    profile:
      $ref: "./profile.yaml#/components/schemas/profile"
    categoryPopulated:
      $ref: "./category.yaml#/components/schemas/categoryPopulated"

    
