name: Setup, Build, Publish, and Deploy

on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy to do
