openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths:
  /category/:
    get:
      security:
        - BearerToken: []
      parameters:
        - $ref: '../security/http.yaml#/components/parameters/bearer'
      tags:
        - 'category'
      summary: list all categories
      description: list all categories for the current user
      responses:
        200:
          $ref: '../responses/categories.yaml#/components/responses/categories'
        401:
          $ref: '../errors/TokenFailed.yaml#/components/responses/TokenFailed'
    post:
      security:
        - BearerToken: []
      parameters:
        - $ref: '../security/http.yaml#/components/parameters/bearer'
      tags:
        - 'category'
      summary: create new category
      description: create new category for the current user
      requestBody:
        required: true
        description: properties like title, color and icon
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  example: Entertainment
                color:
                  type: string
                  example: '#333'
                icon:
                  type: string
                  example: Fun_Face_Icon
      responses:
        201:
          $ref: '../responses/category.yaml#/components/responses/category'
        400:
          $ref: '../errors/SomeFieldsRequired.yaml#/components/responses/SomeFieldsRequired'
        401:
          $ref: '../errors/TokenFailed.yaml#/components/responses/TokenFailed'
  /category/{id}:
    parameters:
      - $ref: '../paths/__parameters.yaml#/components/parameters/byId'
    get:
      security:
        - BearerToken: []
      parameters:
        - $ref: '../security/http.yaml#/components/parameters/bearer'
      tags:
        - 'category'
      summary: get category
      description: get category for the current user
      responses:
        200:
          $ref: '../responses/category.yaml#/components/responses/category'
        401:
          $ref: '../errors/TokenFailed.yaml#/components/responses/TokenFailed'
        404:
          $ref: '../errors/ResourceWasNotFound.yaml#/components/responses/ResourceWasNotFound'
    put:
      security:
        - BearerToken: []
      parameters:
        - $ref: '../security/http.yaml#/components/parameters/bearer'
      requestBody:
        required: true
        description: properties like title, color and icon
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Entertainment
                color:
                  type: string
                  example: '#333'
                icon:
                  type: string
                  example: Fun_Face_Icon
      tags:
        - 'category'
      summary: update category
      description: update category by id
      responses:
        200:
          $ref: '../responses/category.yaml#/components/responses/category'
        401:
          $ref: '../errors/TokenFailed.yaml#/components/responses/TokenFailed'
        404:
          $ref: '../errors/ResourceWasNotFound.yaml#/components/responses/ResourceWasNotFound'
    delete:
      security:
        - BearerToken: []
      parameters:
        - $ref: '../security/http.yaml#/components/parameters/bearer'
      tags:
        - 'category'
      summary: delete category
      description: delete category by id
      responses:
        200:
          description: Ok
          content:
            application/json:
              x-success: true
              schema: {}
        401:
          $ref: '../errors/TokenFailed.yaml#/components/responses/TokenFailed'
        404:
          $ref: '../errors/ResourceWasNotFound.yaml#/components/responses/ResourceWasNotFound'

  /category/{id}/logs:
    parameters:
      - $ref: '../paths/__parameters.yaml#/components/parameters/byId'
    get:
      security:
        - BearerToken: []
      parameters:
        - $ref: '../security/http.yaml#/components/parameters/bearer'
      tags:
        - 'category'
      summary: get all logs
      description: get all logs associated by this category for the current user
      responses:
        200:
          $ref: '../responses/logs.yaml#/components/responses/logs'
        401:
          $ref: '../errors/TokenFailed.yaml#/components/responses/TokenFailed'

servers:
  - url: https://localhost:{port}/api/{version}
    description: development localhost servers
    variables:
      version:
        default: v1
      port:
        default: '8811'
