openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  schemas:
    mongoDoc:  # only in composition
      description: |
        this type is used as composition with other
        type @example:
        ```
        allOf:
        - $ref: '#/components/schemas/mongoDoc'
        - $ref: '#/components/schemas/log'
        ```
      type: object
      required:
        - _id
        - __v
      properties:
        _id: 
           type: string
        __v:
          type: string
          enum:
            - 0
    mongoTime: # only in composition
      description: |
        this type is used as composition with other
        type @example:
        ```
        allOf:
        - $ref: '#/components/schemas/mongoTime'
        - $ref: '#/components/schemas/log'
        ```
      type: object
      required:
        - createdAt
        - updatedAt
      properties:
        createdAt:
          type: string
        updatedAt:
          type: string

    profile:
      allOf:
        - $ref: '#/components/schemas/mongoDoc'
        - type: object
          required:
            - userName
            - email
            - providers
          properties:
            userName: 
              type: string
            email:
              type: string
            providers:
              type: array
              items:
                type: string
                enum:
                  - "local"
                  - "google"
            picture:
              type: string
