openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  parameters:
    byId:
      name: id
      in: path
      description: grap entry by its id, should be place in path as in `to/path/:id/etc`
      required: true
      schema:
        type: string
        example : 63da2a0a643dd3aa49f5c6b1
