openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  responses:
    profile:
      description: Ok
      content:
        application/json: 
          x-success: true
          schema:
            $ref: "#/components/schemas/profile"
  schemas:
    profile:
      $ref: "../schema/profile.yaml#/components/schemas/profile"

 