openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  responses:
    EmailOrPasswordIncorrect:
      description: |
        email/password were/was wrong or not provided
      content:
        application/json:
          x-failed: true
          schema:
            type: object
            properties:
              status:
                type: number
                default: 401
              message:
                description: more details
                example: email/password were/was wrong or not provided
                type: string
              name:
                type: string
                default: EmailOrPasswordIncorrect
              details:
                type: object
