openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
components:
  parameters:
    emailPassword:
      name: Authorization
      in: header
      description: base64 email and password pair
      schema:
        type: string
        example: Basic xxxxxxx=
    bearer:
      name: Authorization
      in: header
      description: can be obtained by `auth/*/*`, in form of eyxxx.xxx.xxx
      schema:
        type: string
        example: Bearer xxxxxxx=


  securitySchemes:
    BasicToken:
      type: http
      scheme: basic
      description: |
        use email and password to gain
        user's profile along with the
        token.
        ```
        curl 'http://exmaple:0000/api/path/to' \
          --H 'Authorization: Basic ZGtAZy5jOjEyMw==' \
        ```  
    BearerToken:
      type: http
      scheme: bearer
      description: |
        this is the standard way to authenticate
        requests, such a token can be obtained via
        emailAuth or googleAuth
        ```
        curl 'http://exmaple:0000/api/path/to' \
          --H 'Authorization: Bearer eyxxx.xxx.xxx' \
        ```  

