openapi: 3.0.0
info:
  title: myPocket
  version: 1.0.0
paths: {}
servers:
  - url: https://localhost:{port}/api/{version}
    description: development localhost servers
    variables:
      version:
        default: v1
      port:
        default: '8811'
