# write a github action's workflow to run e2e test on every push
name: main CI workflows

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_REPO_CACHE_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_REPO_CACHE_TEAM }}

    steps:
      - name: 游닌 Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: 游닌 Install dependencies
        uses: ./.github/actions/pnpm

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: 游닌 Install e2e dependencies
        shell: sh
        run: pnpm install -g concurrently wait-on turbo@latest

      - name: playwright dependencies
        shell: sh
        run: npx playwright install && npx playwright install-deps

      - name: turbo
        run: turbo test build typecheck
        shell: sh

      - name: run rust
        run: ./ci/rust.sh
        shell: bash

      - name: run e2e
        run: ./ci/test-e2e.sh
        shell: bash

      - name: backend integration test
        run: ./ci/test-be.sh
        shell: sh

      # - name: storybook tests
      #   run: ./ci/test-sb.sh
      #   shell: bash

      - name: file changes
        run: '[ $(git diff --name-only HEAD^ HEAD | wc -l) -ne 0 ] && echo there are some changes || echo no changes'
        shell: bash
        if: always()

      - name: clean up
        run: docker compose down
        shell: sh
        if: always()

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: ci
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   steps:

  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: 游닌 Checkout
        uses: actions/checkout@v2

      - name: 游닌 Install dependencies
        uses: ./.github/actions/pnpm

      - name: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          # workingDir: pkgs/ui
          storybookBuildDir: pkgs/ui/storybook-static
          buildScriptName: turbo --filter ui build

      - name: 游닋 Upload e2e report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-report
          path: __tests__/e2e/playwright-report/
          retention-days: 20
