name: Setup, Build, Publish, and Deploy  for production

on:
  push:
    branches:
      - master
    tags:
      - v\d+.\d+.\d+

jobs:
  deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy to do
