# write a github action's workflow to run e2e test on every push
name: e2e test

on: push

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 checkout files
        uses: actions/checkout@v2

      - name: 📥 Install dependencies
        uses: ./.github/actions/pnpm

      - name: 📥 Install e2e dependencies
        run: pnpm install -g concurrently wait-on turbo@latest

      - name: 📥 playwright install
        run: pnpm --filter e2e pn install --with-deps

      - name: 🚀 Run e2e pre scripts
        shell: bash
        run: turbo e2e:build

      - name: 🚀 Run e2e test
        shell: bash
        run: >
          concurrently -n "bg,e2e"
          -c "green,bgBlue.bold"
          -s first --kill-others
          "turbo e2e"
          "sleep 6 && pnpm e2e:dep && pnpm --F e2e run pw test"

      - name: 📤 Upload e2e report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-report
          path: pkgs/e2e/playwright-report/
          retention-days: 20
