name: terraform - setup infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy to do
