name: turborepo

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_REPO_CACHE_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_REPO_CACHE_TEAM }}
    steps:
      - name: 🧪 Test
        run: turbo test

      - name: 🏗 Build
        run: turbo build

      - name: 🔼⏺️⏹️ Typecheck
        run: turbo typecheck
