name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
      name: Test
      timeout-minutes: 15
      runs-on: ubuntu-latest
      env:
       TURBO_TOKEN: ${{ secrets.TURBO_REPO_CACHE_TOKEN }}
       TURBO_TEAM: ${{ secrets.TURBO_REPO_CACHE_TEAM }}
       TURBO_REMOTE_ONLY: true 
      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
           # terraform_version: 0.13.0:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'npm'
 
        - name: Install dependencies
          run: npm install
 
        - name: run deploy
          run: npm run deploy